### ISSUE TITLE
Meta XML for Sym 2.6

### ISSUE THREAD

**Issue by DavidOliver** [designermonkey/incremental_number#8]
Hi. Just reporting that it seems to work fine with Symphony 2.6. Is the XML update just a case of adding a max attribute to the last release?

**Comment by designermonkey** [comment]
Hi @DavidOliver I'll happily take a PR, but this is no longer supported by me. I should offer it to the Symphonists really.

**Comment by DavidOliver** [comment]
Hi @designermonkey. Hope you're well!

I was just looking at the schema in order to make a PR, and I would have thought that as no `max` attribute is present it should show as being compatible with all versions from 2.2 up. @nitriques?

**Comment by nitriques** [comment]
Hey John, I hope you are doing well. If you wish to transfer the repo to the symphonists account it would be cool. Thanks.

**Comment by twiro** [comment]
> _I was just looking at the schema in order to make a PR, and I would have thought that as no max attribute is present it should show as being compatible with all versions from 2.2 up. @nitriques?_

@DavidOliver - you might want to give [this discussion](https://github.com/symphonists/symphony-extensions-network/issues/4) a read. I'll try to sum that up and put it in the [repos readme](https://github.com/symphonists/symphony-extensions-network) as soon as I'll find the time. 

> _**John:** I'll happily take a PR, but this is no longer supported by me. I should offer it to the Symphonists really._

@designermonkey - Would be great if you could follow the brandnew [guide for transferring & adopting extension-repos](https://github.com/symphonists/symphony-extensions-network#extension-adoption). We set up the "Symphony Extensions Network"-repo to help organizing the extension ecosystem and transferring repos is the first task I've set up a kind of "best practice guide" for...

@DavidOliver - want to adopt the extension? ;)

**Comment by DavidOliver** [comment]
> you might want to give this discussion a read.

That was helpful - thanks.

> want to adopt the extension? ;)

I've had a quick look through the code, and while I can't claim to understand all of it I'm willing to have a go if you like.

**Comment by twiro** [comment]
I improved compatibility, readme and meta data and published a new release:

- https://github.com/designermonkey/incremental_number/tree/1.2.0

Thanks for giving me access @designermonkey :)
